In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\tom-i\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
95045,Data Scientist,Remote Perm Data Scientist,"Indianapolis, IN",via WJHL Jobs,Full-time,False,Georgia,2023-05-16 01:26:22,False,False,United States,NaN,NaN,NaN,Insight Global,"['r', 'python', 'sas', 'sas', 'matlab', 'sql',...","{'analyst_tools': ['sas'], 'cloud': ['azure', ..."
343087,Data Analyst,Data Analyst - Top MNC Commercial Bank (up to ...,Hong Kong,via Laimoon.com,Full-time,False,Hong Kong,2023-06-16 23:50:35,True,False,Hong Kong,NaN,NaN,NaN,Hays,"['sas', 'sas', 'flow']","{'analyst_tools': ['sas'], 'other': ['flow'], ..."
757149,Data Analyst,Data Analyst,"Chicago, IL",via Indeed,Full-time,False,"Illinois, United States",2023-05-04 20:02:21,False,False,United States,NaN,NaN,NaN,Insight Global,"['sql', 'sas', 'sas', 'python', 'nosql', 'post...","{'analyst_tools': ['sas', 'power bi', 'tableau..."
590032,Software Engineer,Senior IT Engineer,Netherlands,via BeBee,Full-time and Part-time,False,Netherlands,2023-09-09 09:16:03,False,False,Netherlands,NaN,NaN,NaN,Deutsche Bundesbank,"['sql', 'powershell', 'azure', 'windows']","{'cloud': ['azure'], 'os': ['windows'], 'progr..."
201408,Software Engineer,Fullstack Developer JavaScript 🏆,"Berlin, Germany",via GermanTechJobs,Full-time,False,Germany,2023-01-01 15:36:44,True,False,Germany,NaN,NaN,NaN,Honeypot GmbH,"['javascript', 'php', 'python', 'ruby', 'ruby'...","{'libraries': ['react'], 'programming': ['java..."

In [5]:
df['job_posted_month'] = df['job_posted_date'].dt.strftime('%b')
df.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN,Jun
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",Jan
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",Oct

In [7]:
# now we want to break up the df into 12 differnent dataframes, one for each month. We can do 
# this by using the groupby method.

months = df['job_posted_month'].unique()

{month: month for month in months}

{'Jun': 'Jun',
 'Jan': 'Jan',
 'Oct': 'Oct',
 'Jul': 'Jul',
 'Aug': 'Aug',
 'Nov': 'Nov',
 'Mar': 'Mar',
 'Dec': 'Dec',
 'Apr': 'Apr',
 'Feb': 'Feb',
 'Sep': 'Sep',
 'May': 'May'}

In [12]:
dict_months = {month: df[df['job_posted_month'] == month] for month in months}
dict_months['Jan']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",Jan
20,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,NaN,NaN,NaN,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'sci...","{'libraries': ['pandas', 'numpy', 'scikit-lear...",Jan
39,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,NaN,NaN,NaN,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}",Jan
53,Data Engineer,Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-28 13:07:30,False,True,United States,NaN,NaN,NaN,Verkada,"['sql', 'python', 'aws', 'looker']","{'analyst_tools': ['looker'], 'cloud': ['aws']...",Jan
55,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,NaN,NaN,NaN,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python',...",Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785699,Software Engineer,Simulation Engineer,"Prague, Czechia",via Trabajo.org,Full-time,False,Czechia,2023-01-16 06:35:30,False,False,Czechia,NaN,NaN,NaN,Ricardo Prague s.r.o.,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",Jan
785700,Data Engineer,Data Engineer Ssr/Sr,"Mexico City, CDMX, Mexico",via Trabajo.org,Full-time,False,Mexico,2023-01-12 06:19:55,True,False,Mexico,NaN,NaN,NaN,Tsoft,"['python', 'r', 'azure', 'aws', 'gcp', 'spark'...","{'cloud': ['azure', 'aws', 'gcp'], 'libraries'...",Jan
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN,Jan
785704,Business Analyst,Business Analyst,"Prague, Czechia",via Trabajo.org,Full-time,False,Czechia,2023-01-16 06:35:20,False,False,Czechia,NaN,NaN,NaN,Cleverlance,NaN,NaN,Jan
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",Jan

In [14]:
# quarter 1 data 

df_q1 = pd.concat([dict_months['Jan'], dict_months['Feb'], dict_months['Mar']], ignore_index=True)

In [15]:
df_q1['job_posted_month'].value_counts()

job_posted_month
Jan    91822
Feb    64578
Mar    64084
Name: count, dtype: int64